// Builds the deployable files from the single source file src/app.html.
//   public/index.html  - full web page for static hosting (Vercel, any web server)
//   lib/shared.js      - the urgency prompt + output checker, shared with api/triage.js
//   artifact.html      - the same app body, published as the claude.ai live demo
// Run: node build.js
const fs = require("fs");
const src = fs.readFileSync(__dirname + "/src/app.html", "utf8");

const blocks = [...src.matchAll(/\/\* SHARED-START[^*]*\*\/([\s\S]*?)\/\* SHARED-END \*\//g)].map(m => m[1]);
if (blocks.length !== 3) throw new Error("Expected 3 SHARED blocks, found " + blocks.length);
fs.writeFileSync(__dirname + "/lib/shared.js",
  "// GENERATED by build.js from src/app.html. Edit src/app.html, then run: node build.js\n\"use strict\";\n" +
  blocks.join("\n") + "\nmodule.exports = { LEVELS, RANK, CATEGORIES, SAFETY_QS, buildPrompt, normalizeAI,\n" +
  "  STATUSES, STATUS_LABEL, statusOf, finalUrgency, unitKey, seenAt, fixedAt, applyUpdate, median, findRepeats, computeInsights };\n");

const page = '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n' +
  src.replace(/<meta name="viewport"[^>]*>\n?/, "").replace(/^(<title>[^<]*<\/title>)/, '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n$1') +
  "\n</html>\n";
// put <head>/<body> boundary right after the <style> block
const html = page.replace("</style>\n", "</style>\n</head>\n<body>\n").replace(/\n<\/html>\n$/, "\n</body>\n</html>\n");
fs.writeFileSync(__dirname + "/public/index.html", html);
fs.writeFileSync(__dirname + "/artifact.html", src);
console.log("Built public/index.html, lib/shared.js, artifact.html");
