// Spanish for every English string in CanItWait. English is the key (see shared/i18n.js).
// Register: plain Latin American Spanish, addressing people as "usted". tests/i18n.test.js checks nothing is missing.
export const ES = {
  "Retake it or pick a different one.": "Tómela de nuevo o elija otra.",
  "A clear photo helps maintenance fix it the first time.": "Una foto clara ayuda a mantenimiento a arreglarlo a la primera.",
  "Retake": "Tomar otra",
  "Take photo": "Tomar foto",
  "Choose another": "Elegir otra",
  "Choose from library": "Elegir de la galería",
  "Camera access is blocked. Allow the camera for this site in your browser's settings, or choose a photo from your library.": "El acceso a la cámara está bloqueado. Permita la cámara para este sitio en los ajustes de su navegador, o elija una foto de su galería.",
  "No camera was found on this device. Choose a photo from your library instead.": "No se encontró una cámara en este dispositivo. Elija una foto de su galería.",
  "The camera is being used by another app. Close it and try again, or choose a photo instead.": "Otra app está usando la cámara. Ciérrela e intente de nuevo, o elija una foto.",
  "The camera couldn't start. Choose a photo from your library instead.": "No se pudo iniciar la cámara. Elija una foto de su galería.",
  "Take a photo": "Tomar una foto",
  "Camera preview": "Vista de la cámara",
  "The photo you just took": "La foto que acaba de tomar",
  "Starting camera…": "Iniciando la cámara…",
  "Use photo": "Usar foto",
  "Switch camera": "Cambiar de cámara",
  "Choose from library instead": "Mejor elegir de la galería",
  "Record it again or pick a different one.": "Grábelo de nuevo o elija otro.",
  "Record again": "Grabar de nuevo",
  "Record video": "Grabar video",
  "Choose a video": "Elegir un video",
  "{n} minute ago": "hace {n} minuto",
  "{n} minutes ago": "hace {n} minutos",
  "{n} hour ago": "hace {n} hora",
  "{n} hours ago": "hace {n} horas",
  "{n} day ago": "hace {n} día",
  "{n} days ago": "hace {n} días",
  "{date} at {time}": "{date} a las {time}",
  "{fixed} fixed, {open} still open": "{fixed} arregladas, {open} todavía abiertas",
  "{n} after-hours report": "{n} reporte fuera de horario",
  "{n} after-hours reports": "{n} reportes fuera de horario",
  "{n} day": "{n} día",
  "{n} days": "{n} días",
  "{n} details to fill in, like {example}. You'll be asked when you send.": "{n} detalles por llenar, como {example}. Se le preguntará al enviar.",
  "{n} emergencies not acknowledged": "{n} emergencias sin confirmar",
  "{n} home": "{n} vivienda",
  "{n} homes": "{n} viviendas",
  "{n} minutes": "{n} minutos",
  "{n} more in Insights": "{n} más en Estadísticas",
  "{n} new requests": "{n} solicitudes nuevas",
  "{n} open": "{n} abiertas",
  "{n} properties": "{n} propiedades",
  "{n} property": "{n} propiedad",
  "{n} report": "{n} reporte",
  "{n} reports": "{n} reportes",
  "{n} request in the last 30 days": "{n} solicitud en los últimos 30 días",
  "{n} request in total": "{n} solicitud en total",
  "{n} requests in the last 30 days": "{n} solicitudes en los últimos 30 días",
  "{n} requests in total": "{n} solicitudes en total",
  "{n} return trip": "{n} viaje de regreso",
  "{n} return trips": "{n} viajes de regreso",
  "{n} reviewed request": "{n} solicitud revisada",
  "{n} reviewed requests": "{n} solicitudes revisadas",
  "{n} units, same problem": "{n} unidades, mismo problema",
  "{name} canceled their request": "{name} canceló su solicitud",
  "{name} marked their request {status}": "{name} marcó su solicitud como «{status}»",
  "{name} sent a message": "{name} envió un mensaje",
  "{name} uses CanItWait in {language}. They can translate your messages with one tap.": "{name} usa CanItWait en {language}. Puede traducir sus mensajes con un toque.",
  "{name} will lose access to {place}.": "{name} perderá el acceso a {place}.",
  "{name} will lose access to {place}. Their past requests stay in your inbox.": "{name} perderá el acceso a {place}. Sus solicitudes anteriores se quedan en su bandeja.",
  "{name}, by the resident's own email or text": "{name}, por correo o mensaje de texto del propio residente",
  "{place} (through CanItWait)": "{place} (por CanItWait)",
  "{reports} could wait until morning, out of {total}. Assumes each would otherwise have been a {cost} call-out.": "{reports} podían esperar hasta la mañana, de {total}. Supone que cada uno habría sido una llamada de {cost}.",
  "{reports} in {days}.": "{reports} en {days}.",
  "{unit}: {category} reported {n} times": "{unit}: {category}, reportado {n} veces",
  "{units} units reported it within {days} ({names}). Check shared equipment before sending a tech to each unit.": "{units} unidades lo reportaron en {days} ({names}). Revise el equipo compartido antes de mandar un técnico a cada unidad.",
  "1 detail to fill in, like {example}. You'll be asked when you send.": "1 detalle por llenar, como {example}. Se le preguntará al enviar.",
  "a carbon monoxide alarm": "una alarma de monóxido de carbono",
  "a door that won't lock": "una puerta que no cierra con llave",
  "A few details first": "Primero unos detalles",
  "a gas smell": "olor a gas",
  "A property needs at least one manager. Add another manager first, or delete the property.": "Una propiedad necesita al menos un administrador. Agregue otro administrador primero, o elimine la propiedad.",
  "A slow leak you can catch with a bucket can wait, but should be fixed first thing.": "Una fuga lenta que se puede recoger con un balde puede esperar, pero debe arreglarse a primera hora.",
  "A video was attached. It can be viewed in CanItWait.": "Se adjuntó un video. Se puede ver en CanItWait.",
  "about {cost}": "aproximadamente {cost}",
  "About you": "Sobre usted",
  "Access": "Acceso",
  "Access notes": "Notas de acceso",
  "Acknowledge": "Confirmar",
  "Acknowledge emergency": "Confirmar emergencia",
  "Activity": "Actividad",
  "Add {a} and {b} in Vercel → Settings → Environment Variables, then redeploy. See SETUP.md in the repo.": "Agregue {a} y {b} en Vercel → Settings → Environment Variables y vuelva a publicar. Vea SETUP.md en el repositorio.",
  "Add a few words too, like what you noticed and when it started.": "Agregue también unas palabras, como qué notó y cuándo empezó.",
  "Add a home": "Agregar una vivienda",
  "Add a home to report problems": "Agregue una vivienda para reportar problemas",
  "Add a home whose landlord isn't on CanItWait": "Agregar una vivienda cuyo arrendador no usa CanItWait",
  "Add a password so you can also sign in with {email} and a password.": "Cree una contraseña para poder iniciar sesión también con {email} y una contraseña.",
  "Add a photo": "Agregar una foto",
  "Add a photo or a few words about the problem first.": "Primero agregue una foto o unas palabras sobre el problema.",
  "Add a photo or short video and a few words. You'll get an urgency call and a drafted request to check before anything is sent.": "Agregue una foto o un video corto y unas palabras. Recibirá una evaluación de urgencia y una solicitud redactada para revisar antes de enviar nada.",
  "Add a property": "Agregar una propiedad",
  "Add a property or join a team as a co-manager": "Agregue una propiedad o únase a un equipo como coadministrador",
  "Add a property to get a code for your residents.": "Agregue una propiedad para obtener un código para sus residentes.",
  "Add a short video": "Agregar un video corto",
  "Add details": "Agregar detalles",
  "Add place": "Agregar lugar",
  "Add property": "Agregar propiedad",
  "Add the property name.": "Agregue el nombre de la propiedad.",
  "Add to message and send": "Agregar al mensaje y enviar",
  "Add your first property": "Agregue su primera propiedad",
  "Add your home": "Agregue su vivienda",
  "Add your landlord's email or phone so CanItWait knows where to send requests.": "Agregue el correo o teléfono de su arrendador para que CanItWait sepa adónde enviar las solicitudes.",
  "Add your mobile number above to get emergencies by text.": "Agregue su número de celular arriba para recibir emergencias por texto.",
  "Add your mobile number first.": "Primero agregue su número de celular.",
  "Add your name so your manager knows who sent the request.": "Agregue su nombre para que la administración sepa quién envió la solicitud.",
  "Add your name.": "Agregue su nombre.",
  "Add your property code, or your landlord's email or phone, so CanItWait knows where to send requests.": "Agregue el código de su propiedad, o el correo o teléfono de su arrendador, para que CanItWait sepa adónde enviar las solicitudes.",
  "Add your unit number": "Agregue el número de su unidad",
  "Add your unit so maintenance knows where to go.": "Agregue su unidad para que mantenimiento sepa adónde ir.",
  "Address": "Dirección",
  "after hours": "fuera de horario",
  "After hours {phone}": "Fuera de horario {phone}",
  "After-hours call-out": "Llamada fuera de horario",
  "After-hours call-outs avoided (estimate)": "Llamadas fuera de horario evitadas (estimado)",
  "After-hours emergency line": "Línea de emergencias fuera de horario",
  "After-hours line": "Línea fuera de horario",
  "After-hours line: {phone}. The written request doesn't replace the call.": "Línea fuera de horario: {phone}. La solicitud escrita no reemplaza la llamada.",
  "After-hours reports that could wait": "Reportes fuera de horario que podían esperar",
  "AI accuracy": "Precisión de la IA",
  "AI check": "Revisión con IA",
  "AI suggested: {level}": "La IA sugirió: {level}",
  "AI too high": "IA muy alta",
  "AI too low": "IA muy baja",
  "AI urgency check": "Revisión de urgencia con IA",
  "AI urgency kept by your team": "Urgencia de la IA que su equipo mantuvo",
  "Alarm code, dog in crate, knock first…": "Código de alarma, perro en su jaula, tocar primero…",
  "All": "Todas",
  "All properties": "Todas las propiedades",
  "All set": "Todo listo",
  "All time": "Todo el tiempo",
  "Allowed": "Permitida",
  "Already have an account?": "¿Ya tiene una cuenta?",
  "Also send new requests to": "Enviar también las solicitudes nuevas a",
  "An account with that email already exists. Sign in instead.": "Ya existe una cuenta con ese correo. Inicie sesión.",
  "An inbox sorted by urgency, with photos, unit, and entry permission.": "Una bandeja ordenada por urgencia, con fotos, unidad y permiso de entrada.",
  "Another account already uses that email.": "Otra cuenta ya usa ese correo.",
  "Any \"Yes\" marks it as an emergency, even if the AI disagrees.": "Cualquier «Sí» lo marca como emergencia, aunque la IA no esté de acuerdo.",
  "Any pets in the home?": "¿Hay mascotas en la vivienda?",
  "Anyone with this code can manage {place}, including all of its requests. Share it only with your team.": "Cualquiera con este código puede administrar {place}, incluidas todas sus solicitudes. Compártalo solo con su equipo.",
  "Anytime": "A cualquier hora",
  "Appearance": "Apariencia",
  "Appliance": "Electrodoméstico",
  "Applying the urgency rules": "Aplicando las reglas de urgencia",
  "Apt 214 or Bldg 3, #214": "Apto 214 o Edif. 3, #214",
  "Apt 3B": "Apto 3B",
  "At least 8 characters.": "Al menos 8 caracteres.",
  "Atlanta Gas Light": "Atlanta Gas Light",
  "Back": "Atrás",
  "Back to sign in": "Volver a iniciar sesión",
  "Backup contact name": "Nombre del contacto de respaldo",
  "Backup email": "Correo de respaldo",
  "Backup phone (texts)": "Teléfono de respaldo (mensajes de texto)",
  "Bathroom": "Baño",
  "Bedroom": "Dormitorio",
  "Best times": "Mejores horarios",
  "Best times for a visit": "Mejores horarios para la visita",
  "By creating an account you agree to the {terms} and {privacy}. CanItWait uses AI to suggest urgency, so don't put sensitive personal details in reports.": "Al crear una cuenta acepta los {terms} y la {privacy}. CanItWait usa IA para sugerir la urgencia, así que no incluya datos personales delicados en sus reportes.",
  "Call": "Llamar",
  "Call {name}": "Llamar a {name}",
  "Call 911": "Llamar al 911",
  "Call now": "Llame ahora",
  "Call the after-hours line": "Llamar a la línea fuera de horario",
  "Call your after-hours maintenance line now.": "Llame ahora a su línea de mantenimiento fuera de horario.",
  "Call your after-hours maintenance line.": "Llame a su línea de mantenimiento fuera de horario.",
  "Call your after-hours maintenance line. The written request doesn't replace the call.": "Llame a su línea de mantenimiento fuera de horario. La solicitud escrita no reemplaza la llamada.",
  "Call your property's after-hours maintenance line.": "Llame a la línea de mantenimiento fuera de horario de su propiedad.",
  "Can maintenance enter if you're not home?": "¿Puede entrar mantenimiento si usted no está?",
  "Can't lock your front door?": "¿No puede cerrar con llave la puerta de entrada?",
  "Cancel": "Cancelar",
  "Cancel request": "Cancelar solicitud",
  "Canceled": "Cancelada",
  "CanItWait drafts each request, then opens your email or texting app so you can send it to your landlord.": "CanItWait redacta cada solicitud y luego abre su app de correo o de mensajes para que se la envíe a su arrendador.",
  "CanItWait isn't connected yet": "CanItWait aún no está conectado",
  "Category": "Categoría",
  "Ceiling / Walls / Floors": "Techo / Paredes / Pisos",
  "Change": "Cambiar",
  "Change email": "Cambiar correo",
  "Change password": "Cambiar contraseña",
  "Change urgency": "Cambiar urgencia",
  "changed the urgency to {level}": "cambió la urgencia a {level}",
  "Check urgency": "Revisar urgencia",
  "Check your email": "Revise su correo",
  "Checking urgency": "Revisando la urgencia",
  "Choose a password different from your current one.": "Elija una contraseña distinta a la actual.",
  "Choose a password different from your old one.": "Elija una contraseña distinta a la anterior.",
  "Choose how to send it to {name}. Your email or texting app opens with everything filled in; tap send there.": "Elija cómo enviársela a {name}. Su app de correo o de mensajes se abre con todo listo; toque enviar ahí.",
  "Clear urgency.": "Urgencia clara.",
  "Close": "Cerrar",
  "Close photo": "Cerrar foto",
  "Closed": "Cerradas",
  "Co-managers": "Coadministradores",
  "Complete on arrival": "Completas al llegar",
  "Confirm new password": "Confirme la contraseña nueva",
  "Confirm your email first. Check your inbox for the link.": "Primero confirme su correo. Busque el enlace en su bandeja de entrada.",
  "Connect": "Conectar",
  "Connect with your property's code, or add your landlord's contact details.": "Conéctese con el código de su propiedad, o agregue los datos de contacto de su arrendador.",
  "Connect your home": "Conecte su vivienda",
  "Connect your home first": "Primero conecte su vivienda",
  "Connected to {place}": "Conectado a {place}",
  "Connected. You can sign in with Google.": "Conectado. Puede iniciar sesión con Google.",
  "Contact support": "Contactar a soporte",
  "Continue": "Continuar",
  "Continue to send": "Continuar para enviar",
  "Continue with Google": "Continuar con Google",
  "Copied": "Copiado",
  "Copy": "Copiar",
  "Copy as work order": "Copiar como orden de trabajo",
  "Copy invite link": "Copiar enlace de invitación",
  "Couldn't delete the account. Check your connection and try again.": "No se pudo eliminar la cuenta. Revise su conexión e intente de nuevo.",
  "Create a free account": "Crear una cuenta gratis",
  "Create a property to get a resident code. Requests from residents who use it land here.": "Cree una propiedad para obtener un código para residentes. Las solicitudes de quienes lo usen llegan aquí.",
  "Create account": "Crear cuenta",
  "Create an account": "Crear una cuenta",
  "Create new codes": "Crear códigos nuevos",
  "Create new codes?": "¿Crear códigos nuevos?",
  "Create property": "Crear propiedad",
  "Create your account": "Cree su cuenta",
  "Created your account with Google? Use Continue with Google above. Otherwise reset your password below.": "¿Creó su cuenta con Google? Use «Continuar con Google» arriba. Si no, restablezca su contraseña abajo.",
  "Current email:": "Correo actual:",
  "Current password": "Contraseña actual",
  "Dark mode": "Modo oscuro",
  "Delete account": "Eliminar cuenta",
  "Delete property": "Eliminar propiedad",
  "Delete this property?": "¿Eliminar esta propiedad?",
  "Delete your account?": "¿Eliminar su cuenta?",
  "Describe": "Describir",
  "Details": "Detalles",
  "Didn't get it? Check spam, or wait a minute and try signing in.": "¿No le llegó? Revise el correo no deseado, o espere un minuto e intente iniciar sesión.",
  "Do you smell gas or rotten eggs?": "¿Huele a gas o a huevos podridos?",
  "Don't wait on the app. If anyone is in danger, call 911. Otherwise call the after-hours line.": "No espere a la app. Si alguien está en peligro, llame al 911. Si no, llame a la línea fuera de horario.",
  "Done": "Listo",
  "Doors / Locks / Windows": "Puertas / Cerraduras / Ventanas",
  "Download as CSV": "Descargar como CSV",
  "Downloaded {n} requests": "Se descargaron {n} solicitudes",
  "Drafting your request": "Redactando su solicitud",
  "Easier on the eyes at night. Saved on this device.": "Más cómodo para la vista de noche. Se guarda en este dispositivo.",
  "Edit": "Editar",
  "Edit home": "Editar vivienda",
  "Edit property": "Editar propiedad",
  "Electrical": "Electricidad",
  "Email": "Correo electrónico",
  "Email {name}": "Enviar correo a {name}",
  "Email and text can't attach the photo automatically. Add it from your camera roll in the message.": "El correo y los mensajes no pueden adjuntar la foto automáticamente. Agréguela desde su galería en el mensaje.",
  "Email changed": "Correo cambiado",
  "Email updates": "Avisos por correo",
  "Email updates off": "Avisos por correo desactivados",
  "Email updates on": "Avisos por correo activados",
  "Emergencies": "Emergencias",
  "Emergencies at your properties are texted to {phone}, when texting is set up for CanItWait.": "Las emergencias de sus propiedades se envían por texto a {phone}, cuando los mensajes de texto están configurados en CanItWait.",
  "Emergencies can't be missed.": "Las emergencias no se pierden.",
  "Emergencies, new requests, status changes and messages on this device.": "Emergencias, solicitudes nuevas, cambios de estado y mensajes en este dispositivo.",
  "Emergency": "Emergencia",
  "Emergency backup and forwarding": "Respaldo de emergencias y reenvío",
  "Emergency not acknowledged: {title}": "Emergencia sin confirmar: {title}",
  "Emergency still not acknowledged: {title}": "Emergencia todavía sin confirmar: {title}",
  "Emergency texts": "Mensajes de texto de emergencia",
  "Emergency texts off": "Mensajes de emergencia desactivados",
  "Emergency texts on": "Mensajes de emergencia activados",
  "Emergency, urgent, or routine, with the reason and safe steps until it's fixed.": "Emergencia, urgente o rutina, con la razón y pasos seguros mientras lo arreglan.",
  "Emergency: {title}": "Emergencia: {title}",
  "Emergency.": "Emergencia.",
  "English": "inglés",
  "English y español.": "English y español.",
  "Enlarge photo": "Agrandar foto",
  "Enter a valid email address.": "Escriba un correo electrónico válido.",
  "Enter the co-manager code another manager shared with you. It starts with M-.": "Escriba el código de coadministrador que le compartió otro administrador. Empieza con M-.",
  "Enter the code from your property manager so your requests go straight to them.": "Escriba el código que le dio la administración para que sus solicitudes les lleguen directamente.",
  "Enter the full code, like 7KQ2-HXPM.": "Escriba el código completo, como 7KQ2-HXPM.",
  "Enter your current password.": "Escriba su contraseña actual.",
  "Enter your email and password.": "Escriba su correo y su contraseña.",
  "Entry allowed": "Se permite entrar",
  "Entry if not home": "Entrada si no está",
  "Entry notes": "Notas de entrada",
  "Escalate after": "Escalar después de",
  "Escalated to the backup contact.": "Se escaló al contacto de respaldo.",
  "Evenings": "Noches",
  "Every manager gets emergencies by phone notification, email and (if set up) text. If nobody acknowledges one in time, CanItWait texts and emails your backup contact and tells the resident to call.": "Cada administrador recibe las emergencias por notificación en el teléfono, correo y (si está configurado) mensaje de texto. Si nadie confirma una a tiempo, CanItWait le escribe por texto y correo a su contacto de respaldo y le dice al residente que llame.",
  "Everything you've reported, with the latest status.": "Todo lo que ha reportado, con el estado más reciente.",
  "Example of a result. Sign up to check your own.": "Ejemplo de un resultado. Regístrese para revisar el suyo.",
  "Extra technician trip": "Viaje adicional del técnico",
  "Feeds the first-visit fix rate in Insights.": "Alimenta la tasa de arreglos en la primera visita en Estadísticas.",
  "Filter": "Filtro",
  "Fire / Smoke": "Fuego / Humo",
  "Fixed": "Arreglada",
  "Fixed and canceled requests show up here.": "Aquí aparecen las solicitudes arregladas y canceladas.",
  "Fixed on first visit": "Arreglado en la primera visita",
  "Fixed on the first visit": "Arreglado en la primera visita",
  "Fixed on the first visit?": "¿Se arregló en la primera visita?",
  "For {email}": "Para {email}",
  "For example, your AppFolio, Buildium or Yardi maintenance inbox, or a shared team address. Each new request arrives there as a work order.": "Por ejemplo, su bandeja de mantenimiento de AppFolio, Buildium o Yardi, o un correo compartido del equipo. Cada solicitud nueva llega ahí como orden de trabajo.",
  "For renters and property managers": "Para inquilinos y administradores de propiedades",
  "Forgot it? Email me a reset link": "¿La olvidó? Envíenme un enlace por correo",
  "Forgot your password?": "¿Olvidó su contraseña?",
  "Free for renters and property managers.": "Gratis para inquilinos y administradores de propiedades.",
  "Full name": "Nombre completo",
  "Gas": "Gas",
  "Gate code 1234, park in visitor spots, building B side door": "Código del portón 1234, estacione en visitas, puerta lateral del edificio B",
  "Gate, lockbox or parking notes": "Notas de portón, caja de llaves o estacionamiento",
  "Get an inbox sorted by urgency and invite your residents with a code.": "Reciba una bandeja ordenada por urgencia e invite a sus residentes con un código.",
  "Give this place a name, like “My apartment”.": "Póngale un nombre a este lugar, como «Mi apartamento».",
  "Google sign-in isn't set up yet. Use email for now.": "El inicio de sesión con Google aún no está configurado. Por ahora use su correo.",
  "Hallway": "Pasillo",
  "Has video": "Tiene video",
  "Heating / AC": "Calefacción / Aire acondicionado",
  "Helps maintenance plan the visit. All optional, and remembered for next time on this phone.": "Ayuda a mantenimiento a planear la visita. Todo es opcional y se recuerda en este teléfono para la próxima vez.",
  "History": "Historial",
  "Home": "Vivienda",
  "Home added": "Vivienda agregada",
  "Homes and properties": "Viviendas y propiedades",
  "How the AI's urgency compares with your team's final call. Under-calls matter most for safety.": "Cómo se compara la urgencia de la IA con la decisión final de su equipo. Lo más importante para la seguridad es cuando la IA se queda corta.",
  "How will you use CanItWait?": "¿Cómo va a usar CanItWait?",
  "How your maintenance is going, from your own requests.": "Cómo va su mantenimiento, según sus propias solicitudes.",
  "I changed it to {level}.": "Yo la cambié a {level}.",
  "I manage properties": "Administro propiedades",
  "I rent a home": "Alquilo una vivienda",
  "If {email} has an account, a reset link is on its way.": "Si {email} tiene una cuenta, le estamos enviando un enlace para restablecerla.",
  "If a code was shared with the wrong person, create new codes. People who already joined stay connected.": "Si un código llegó a la persona equivocada, cree códigos nuevos. Quienes ya se unieron siguen conectados.",
  "If anyone is in danger, call 911. Otherwise call the after-hours line: {phone}.": "Si alguien está en peligro, llame al 911. Si no, llame a la línea fuera de horario: {phone}.",
  "If anyone is in danger, call 911. Otherwise call your property's after-hours line.": "Si alguien está en peligro, llame al 911. Si no, llame a la línea fuera de horario de su propiedad.",
  "If there's fire or heavy smoke, get out first, then call 911.": "Si hay fuego o mucho humo, salga primero y luego llame al 911.",
  "In progress": "En progreso",
  "Inbox": "Bandeja",
  "Insights": "Estadísticas",
  "Invite residents": "Invitar residentes",
  "Is a carbon monoxide alarm going off?": "¿Está sonando una alarma de monóxido de carbono?",
  "Is any of this happening right now?": "¿Está pasando algo de esto ahora mismo?",
  "It can wait until morning, so you can go to bed.": "Puede esperar hasta la mañana, así que puede irse a dormir.",
  "It may have been deleted, or you no longer have access to it.": "Puede que se haya eliminado o que ya no tenga acceso.",
  "It started [when it started].": "Empezó [cuándo empezó].",
  "It's fixed": "Ya está arreglado",
  "It's happening now: make it an emergency": "Está pasando ahora: marcar como emergencia",
  "Join {place} on CanItWait": "Únase a {place} en CanItWait",
  "Join a team": "Unirse a un equipo",
  "Join a team with a co-manager code": "Unirse a un equipo con un código de coadministrador",
  "Join another manager's team": "Unirse al equipo de otro administrador",
  "Join as co-manager": "Unirse como coadministrador",
  "Join property": "Unirse a la propiedad",
  "Join with a code": "Unirse con un código",
  "Join with a property code": "Unirse con un código de propiedad",
  "Join your team": "Únase a su equipo",
  "just now": "ahora",
  "Keep the bathroom light off if water is near it.": "Deje apagada la luz del baño si hay agua cerca.",
  "Keep videos to {s} seconds or less.": "Los videos deben durar {s} segundos o menos.",
  "Kitchen": "Cocina",
  "landlord": "arrendador",
  "Landlord or manager name": "Nombre del arrendador o administrador",
  "Language": "Idioma",
  "Last 30 days": "Últimos 30 días",
  "Laundry": "Lavandería",
  "Leave": "Salir",
  "Leave now. Don't flip switches, light anything, or start a car. Call from outside.": "Salga ahora. No toque interruptores, no prenda nada ni encienda un carro. Llame desde afuera.",
  "Leave property": "Salir de la propiedad",
  "Leave this property?": "¿Salir de esta propiedad?",
  "Leaving a property stops new reports there. Requests you already sent stay in your list.": "Al salir de una propiedad ya no podrá reportar ahí. Las solicitudes que ya envió se quedan en su lista.",
  "Legal": "Legal",
  "Less serious than it looked": "Menos grave de lo que parecía",
  "Link expired": "El enlace venció",
  "Living room": "Sala",
  "Load a separate sample property with six weeks of requests, repeat problems and a filled-in Insights screen. Delete it any time.": "Cargue una propiedad de ejemplo aparte con seis semanas de solicitudes, problemas repetidos y Estadísticas completas. Bórrela cuando quiera.",
  "Load sample data": "Cargar datos de ejemplo",
  "Loading": "Cargando",
  "Loading CanItWait": "Cargando CanItWait",
  "Look for the root cause instead of another patch.": "Busque la causa de fondo en vez de otro arreglo rápido.",
  "Main": "Principal",
  "Maintenance": "Mantenimiento",
  "Maintenance request": "Solicitud de mantenimiento",
  "Maintenance request record": "Constancia de solicitud de mantenimiento",
  "Maintenance request records": "Constancias de solicitudes de mantenimiento",
  "Maintenance should pick this up first thing in the morning.": "Mantenimiento debería atender esto a primera hora de la mañana.",
  "Maintenance will likely ask": "Mantenimiento probablemente preguntará",
  "Maintenance will see that you canceled it.": "Mantenimiento verá que usted la canceló.",
  "Manage a property": "Administrar una propiedad",
  "Manager": "Administración",
  "Manager since {date}": "Administrador desde {date}",
  "Managers see emergencies first.": "La administración ve primero las emergencias.",
  "Mark as seen": "Marcar como vista",
  "Mark fixed": "Marcar arreglada",
  "Marked {status}": "Marcada como «{status}»",
  "marked it {status}": "la marcó como «{status}»",
  "marked it fixed": "la marcó como arreglada",
  "marked it fixed (took more than one visit)": "la marcó como arreglada (tomó más de una visita)",
  "marked it fixed on the first visit": "la marcó como arreglada en la primera visita",
  "Matched": "Coincidió",
  "Median {time} to first response": "Mediana de {time} hasta la primera respuesta",
  "Median time to fix": "Tiempo mediano para arreglar",
  "Message": "Mensaje",
  "Message {name}…": "Escribirle a {name}…",
  "Message maintenance…": "Escribirle a mantenimiento…",
  "Message to maintenance": "Mensaje para mantenimiento",
  "Mobile number": "Número de celular",
  "My apartment": "Mi apartamento",
  "My homes": "Mis viviendas",
  "My landlord doesn't use CanItWait": "Mi arrendador no usa CanItWait",
  "My requests": "Mis solicitudes",
  "Name for this place": "Nombre de este lugar",
  "Needs manual review": "Necesita revisión manual",
  "New": "Nueva",
  "New codes created. Old codes no longer work.": "Se crearon códigos nuevos. Los anteriores ya no funcionan.",
  "New email": "Correo nuevo",
  "New message: {title}": "Mensaje nuevo: {title}",
  "New password": "Contraseña nueva",
  "New request ({level}): {title}": "Nueva solicitud ({level}): {title}",
  "New requests from your residents appear here automatically, emergencies first.": "Las solicitudes nuevas de sus residentes aparecen aquí automáticamente, primero las emergencias.",
  "New requests, status changes and messages, sent to {email}.": "Solicitudes nuevas, cambios de estado y mensajes, enviados a {email}.",
  "New to CanItWait?": "¿Es nuevo en CanItWait?",
  "No": "No",
  "No address": "Sin dirección",
  "No homes yet": "Aún no hay viviendas",
  "No one acknowledged within {n} minutes. CanItWait alerted the backup contact and reminded the team.": "Nadie confirmó en {n} minutos. CanItWait avisó al contacto de respaldo y le recordó al equipo.",
  "No one acknowledged within {n} minutes. CanItWait reminded the team.": "Nadie confirmó en {n} minutos. CanItWait le recordó al equipo.",
  "No open requests": "No hay solicitudes abiertas",
  "No properties yet": "Aún no hay propiedades",
  "No requests in the last 30 days": "No hay solicitudes en los últimos 30 días",
  "No requests yet": "Aún no hay solicitudes",
  "No residents yet": "Aún no hay residentes",
  "No response times yet": "Aún no hay tiempos de respuesta",
  "No unit": "Sin unidad",
  "Not allowed": "No permitida",
  "Not answered": "Sin respuesta",
  "Not set. You sign in with Google.": "No está configurada. Usted inicia sesión con Google.",
  "Note": "Nota",
  "Note from {name}": "Nota de {name}",
  "Note to the resident": "Nota para el residente",
  "Nothing closed yet": "Nada cerrado todavía",
  "Nothing here": "No hay nada aquí",
  "Nothing repeating in the last 60 days. CanItWait flags a unit that reports the same kind of problem twice, and 3 or more units reporting the same problem within a week.": "Nada repetido en los últimos 60 días. CanItWait marca una unidad que reporta el mismo tipo de problema dos veces, y 3 o más unidades que reportan el mismo problema en una semana.",
  "Notifications": "Notificaciones",
  "Notifications are blocked for CanItWait in this browser's settings.": "Las notificaciones de CanItWait están bloqueadas en los ajustes de este navegador.",
  "Notifications off for this device": "Notificaciones desactivadas en este dispositivo",
  "Notifications on for this device": "Notificaciones activadas en este dispositivo",
  "Numbers appear here as residents send requests and your team updates them.": "Los números aparecen aquí a medida que los residentes envían solicitudes y su equipo las actualiza.",
  "Of {reviewed}, how many kept the urgency the AI suggested. Change a request's urgency in the inbox when it's wrong.": "De {reviewed}, cuántas mantuvieron la urgencia que sugirió la IA. Cambie la urgencia de una solicitud en la bandeja cuando esté mal.",
  "On iPhone, first tap Share, then Add to Home Screen, and open CanItWait from there.": "En iPhone, primero toque Compartir, luego «Agregar a pantalla de inicio», y abra CanItWait desde ahí.",
  "On-call supervisor": "Supervisor de guardia",
  "Only managers can change urgency": "Solo la administración puede cambiar la urgencia",
  "Only managers can do this": "Solo la administración puede hacer esto",
  "Only the property owner can remove a manager": "Solo el dueño de la propiedad puede quitar a un administrador",
  "Open": "Abiertas",
  "Open in CanItWait": "Abrir en CanItWait",
  "Open requests, emergencies first. Updates live.": "Solicitudes abiertas, primero las emergencias. Se actualiza en vivo.",
  "Open to acknowledge.": "Abra para confirmar.",
  "Opened. Send it there": "Abierto. Envíelo desde ahí",
  "optional": "opcional",
  "Optional. Up to {s} seconds, for leaks, noises or things that come and go.": "Opcional. Hasta {s} segundos, para fugas, ruidos o cosas que van y vienen.",
  "or": "o",
  "or join a team": "o únase a un equipo",
  "Other": "Otro",
  "out of {reports}. Add your call-out cost below to see an estimated savings.": "de {reports}. Agregue su costo por llamada abajo para ver un ahorro estimado.",
  "Outside": "Afuera",
  "Password": "Contraseña",
  "Password changed": "Contraseña cambiada",
  "Password set. You can now sign in with your email too.": "Contraseña creada. Ahora también puede iniciar sesión con su correo.",
  "Password updated": "Contraseña actualizada",
  "Period": "Período",
  "Permission to enter": "Permiso para entrar",
  "Pests": "Plagas",
  "Pets": "Mascotas",
  "Pets in the home": "Mascotas en la vivienda",
  "Phone alerts for the team, and a backup contact if nobody answers.": "Alertas al teléfono del equipo y un contacto de respaldo si nadie responde.",
  "Phone notifications": "Notificaciones en el teléfono",
  "Photo": "Foto",
  "Photo added": "Foto agregada",
  "Photo of the problem": "Foto del problema",
  "Photo or video attached in CanItWait": "Foto o video adjunto en CanItWait",
  "Photos and descriptions are sent to Google's Gemini AI to suggest urgency and to translate when you ask. On the free tier Google may use them to improve its products, so don't include sensitive personal details.": "Las fotos y descripciones se envían a la IA Gemini de Google para sugerir la urgencia y para traducir cuando usted lo pide. En el plan gratuito, Google puede usarlas para mejorar sus productos, así que no incluya datos personales delicados.",
  "Pick a reason so your team can see why it changed.": "Elija una razón para que su equipo vea por qué cambió.",
  "Pick a visit date and time.": "Elija la fecha y hora de la visita.",
  "Pick the level that fits.": "Elija el nivel que corresponda.",
  "Picking up where you left off…": "Retomando donde se quedó…",
  "Plumbing / Water": "Plomería / Agua",
  "Possible building-wide problem: {category}": "Posible problema en todo el edificio: {category}",
  "Prepared {time}": "Preparada el {time}",
  "Print or save as PDF": "Imprimir o guardar como PDF",
  "Print record": "Imprimir constancia",
  "Privacy": "Privacidad",
  "Privacy Policy": "Política de privacidad",
  "Profile": "Perfil",
  "Profile saved": "Perfil guardado",
  "Properties": "Propiedades",
  "Properties I manage": "Propiedades que administro",
  "Property": "Propiedad",
  "Property code": "Código de la propiedad",
  "Property deleted": "Propiedad eliminada",
  "Property name": "Nombre de la propiedad",
  "Property name is required": "El nombre de la propiedad es obligatorio",
  "Property not found": "No se encontró la propiedad",
  "Put a bucket or towels under the drip.": "Ponga un balde o toallas debajo de la gotera.",
  "Reading your photo and description": "Leyendo su foto y descripción",
  "Recorded when you mark a request fixed": "Se registra al marcar una solicitud como arreglada",
  "Records": "Constancias",
  "Remove": "Quitar",
  "Remove photo": "Quitar foto",
  "Remove this person?": "¿Quitar a esta persona?",
  "Remove this place": "Quitar este lugar",
  "Remove video": "Quitar video",
  "Removed": "Eliminado",
  "Reopen": "Reabrir",
  "Repeat": "Repetido",
  "Repeat · {nth} of {count} in {days}": "Repetido · {nth} de {count} en {days}",
  "Repeat problems": "Problemas repetidos",
  "Report": "Reportar",
  "Report a problem": "Reportar un problema",
  "Report for any of these. If you rent in more than one place, add each one.": "Reporte para cualquiera de estas. Si alquila en más de un lugar, agregue cada uno.",
  "Report maintenance problems for {place} with CanItWait (English or Spanish). Your code is {code}.": "Reporte problemas de mantenimiento de {place} con CanItWait (en inglés o español). Su código es {code}.",
  "Report problems, get an urgency call, and track repairs.": "Reporte problemas, sepa qué tan urgentes son y siga las reparaciones.",
  "Report something else": "Reportar otra cosa",
  "Report what broke. Know how urgent it is.": "Reporte lo que se dañó. Sepa qué tan urgente es.",
  "Reported": "Reportado",
  "Reported {ago}. Contact the resident now.": "Reportada {ago}. Contacte al residente ahora.",
  "Reported {time}": "Reportado {time}",
  "Reported by": "Reportado por",
  "Request": "Solicitud",
  "Request not found": "No se encontró la solicitud",
  "Requests": "Solicitudes",
  "Requests by category": "Solicitudes por categoría",
  "Requests go by email": "Las solicitudes van por correo",
  "Requests go by email or text": "Las solicitudes van por correo o mensaje de texto",
  "Requests go by text": "Las solicitudes van por mensaje de texto",
  "Requests go to the CanItWait inbox": "Las solicitudes van a la bandeja de CanItWait",
  "Requests your team made more urgent": "Solicitudes que su equipo subió de urgencia",
  "Reschedule": "Reprogramar",
  "Reset link sent to {email}": "Enlace para restablecer enviado a {email}",
  "Reset password": "Restablecer contraseña",
  "Reset your password": "Restablezca su contraseña",
  "Resident": "Residente",
  "Resident changed from {level}": "El residente la cambió de {level}",
  "Resident gave more details": "El residente dio más detalles",
  "Resident sent: {level}": "El residente envió: {level}",
  "Residents ({n})": "Residentes ({n})",
  "Residents enter this code when they sign up, or open the link.": "Los residentes escriben este código al registrarse, o abren el enlace.",
  "Residents see this when a report is an emergency.": "Los residentes lo ven cuando un reporte es una emergencia.",
  "Review": "Revisar",
  "Routine": "Rutina",
  "Safety risk the AI missed": "Riesgo de seguridad que la IA no vio",
  "Same unit, same kind of problem": "Misma unidad, mismo tipo de problema",
  "Sample property added. Delete it from Properties when you're done.": "Se agregó la propiedad de ejemplo. Bórrela desde Propiedades cuando termine.",
  "Sample property loaded? Delete it from Properties when you're done.": "¿Cargó la propiedad de ejemplo? Bórrela desde Propiedades cuando termine.",
  "Save": "Guardar",
  "Save a record (PDF)": "Guardar constancia (PDF)",
  "Save changes": "Guardar cambios",
  "Save password": "Guardar contraseña",
  "Save urgency": "Guardar urgencia",
  "Saved": "Guardado",
  "Saved to your requests": "Guardada en sus solicitudes",
  "Schedule return visit": "Programar otra visita",
  "Schedule visit": "Programar visita",
  "Scheduled": "Programada",
  "scheduled a visit": "programó una visita",
  "scheduled a visit for {time}": "programó una visita para el {time}",
  "scheduled a visit for {time} with {tech}": "programó una visita para el {time} con {tech}",
  "Security": "Seguridad",
  "Seen": "Vista",
  "Seen by manager": "Vista por la administración",
  "Select a request to see details, change its status, and message the resident.": "Seleccione una solicitud para ver los detalles, cambiar su estado y escribirle al residente.",
  "Send": "Enviar",
  "Send a new link": "Enviar un enlace nuevo",
  "Send it tonight. It can wait until morning, so you can go to bed.": "Envíela esta noche. Puede esperar hasta la mañana, así que puede irse a dormir.",
  "Send it whenever. It will be scheduled during business hours.": "Envíela cuando quiera. Se programará en horario laboral.",
  "Send message": "Enviar mensaje",
  "Send reset link": "Enviar enlace",
  "Send to {place}": "Enviar a {place}",
  "Send with another app…": "Enviar con otra app…",
  "Send without them": "Enviar sin ellos",
  "Sending…": "Enviando…",
  "Sent": "Enviada",
  "Sent outside CanItWait": "Enviada fuera de CanItWait",
  "sent the request": "envió la solicitud",
  "Sent to": "Enviado a",
  "Sent to {place}": "Enviada a {place}",
  "Sent with a photo and no blanks left to fill": "Enviadas con foto y sin espacios en blanco",
  "Sent without the AI urgency check.": "Enviada sin la revisión de urgencia con IA.",
  "Set": "Crear",
  "Set a new password": "Cree una contraseña nueva",
  "Set a password": "Crear una contraseña",
  "Set password": "Crear contraseña",
  "Settings": "Ajustes",
  "Share": "Compartir",
  "Share each property's code with its residents. Invite co-managers with the team code.": "Comparta el código de cada propiedad con sus residentes. Invite a otros administradores con el código del equipo.",
  "Share the invite code above. Residents appear here as they join.": "Comparta el código de invitación de arriba. Los residentes aparecen aquí a medida que se unen.",
  "Shared with managers of properties you join. If you manage properties, your residents see it too.": "Se comparte con la administración de las propiedades a las que se une. Si usted administra propiedades, sus residentes también lo ven.",
  "Show original": "Ver original",
  "Shown when a report is an emergency.": "Se muestra cuando un reporte es una emergencia.",
  "Shows once your team has reviewed requests.": "Aparece cuando su equipo haya revisado solicitudes.",
  "Sign in": "Iniciar sesión",
  "Sign in first": "Primero inicie sesión",
  "Sign in with your password, or use Continue with Google if that's how you created it.": "Inicie sesión con su contraseña, o use «Continuar con Google» si así la creó.",
  "Sign out": "Cerrar sesión",
  "Sign out everywhere": "Cerrar sesión en todos lados",
  "Sign out everywhere?": "¿Cerrar sesión en todos lados?",
  "Sign out on every phone and computer, including this one.": "Cierra la sesión en todos los teléfonos y computadoras, incluido este.",
  "Sign-in and security": "Inicio de sesión y seguridad",
  "Skip the AI and fill it in myself": "Saltar la IA y llenarlo yo",
  "smoke, sparks or burning": "humo, chispas u olor a quemado",
  "Smoke, sparks, or a burning smell?": "¿Humo, chispas u olor a quemado?",
  "Snap a photo and CanItWait tells you whether to call now or wait until morning, then writes a request maintenance can act on the first time.": "Tome una foto y CanItWait le dice si debe llamar ahora o esperar hasta la mañana, y redacta una solicitud que mantenimiento puede atender a la primera.",
  "Someone": "Alguien",
  "Something went wrong": "Algo salió mal",
  "Spanish": "español",
  "Spoke with the resident; water is contained.": "Hablé con el residente; el agua está contenida.",
  "Start over": "Empezar de nuevo",
  "Start work": "Empezar trabajo",
  "Status": "Estado",
  "Step {n} of 3": "Paso {n} de 3",
  "Stop and fill it in myself": "Parar y llenarlo yo",
  "Suggested by the AI. Change it if it's wrong.": "Sugerido por la IA. Cámbielo si está mal.",
  "Take one now or choose from your photos.": "Tome una ahora o elija de sus fotos.",
  "Tap to change it.": "Toque para cambiarla.",
  "Technician": "Técnico",
  "Terms": "Términos",
  "Terms of Service": "Términos del servicio",
  "Text {name}": "Enviar mensaje a {name}",
  "That code does not match a property. Check it with your manager.": "Ese código no coincide con ninguna propiedad. Verifíquelo con la administración.",
  "That email and password don't match.": "El correo y la contraseña no coinciden.",
  "That email doesn't look right.": "Ese correo no parece correcto.",
  "That file is too large.": "Ese archivo es demasiado grande.",
  "That photo couldn't be read. Try a JPG or PNG, or take a new one with the camera.": "No se pudo leer esa foto. Pruebe con un JPG o PNG, o tome una nueva con la cámara.",
  "That video couldn't be read. Try recording it again with the camera.": "No se pudo leer ese video. Intente grabarlo de nuevo con la cámara.",
  "That video is too large. Keep it under {mb} MB (about 30 seconds).": "Ese video es demasiado grande. Que pese menos de {mb} MB (unos 30 segundos).",
  "That's already your email.": "Ese ya es su correo.",
  "The AI check couldn't be reached.": "No se pudo conectar con la revisión con IA.",
  "The AI check is busy right now.": "La revisión con IA está ocupada en este momento.",
  "The AI check isn't set up on the server yet.": "La revisión con IA aún no está configurada en el servidor.",
  "The AI looks at a still from your video. Your manager gets the whole video.": "La IA mira una imagen de su video. La administración recibe el video completo.",
  "The AI said {level}; your safety answers make it an emergency.": "La IA dijo {level}; sus respuestas de seguridad lo convierten en emergencia.",
  "The app, AI results, emails and notifications use this language. Requests and messages in another language can be translated with one tap.": "La app, los resultados de la IA, los correos y las notificaciones usan este idioma. Las solicitudes y mensajes en otro idioma se pueden traducir con un toque.",
  "The backup email doesn't look right.": "El correo de respaldo no parece correcto.",
  "The current resident and co-manager codes stop working right away. Share the new ones with anyone who still needs to join.": "Los códigos actuales de residentes y coadministradores dejan de funcionar de inmediato. Comparta los nuevos con quien todavía necesite unirse.",
  "The forwarding email doesn't look right.": "El correo de reenvío no parece correcto.",
  "The manager gets an update.": "La administración recibe un aviso.",
  "The message to maintenance is empty. Add a sentence about the problem.": "El mensaje para mantenimiento está vacío. Agregue una frase sobre el problema.",
  "The new passwords don't match.": "Las contraseñas nuevas no coinciden.",
  "The passwords don't match.": "Las contraseñas no coinciden.",
  "The resident gets an update.": "El residente recibe un aviso.",
  "Their email": "Su correo",
  "Their phone for texts": "Su teléfono para mensajes de texto",
  "Then send this report so there's a written record with your photo.": "Después envíe este reporte para que quede constancia por escrito con su foto.",
  "This browser can't show notifications. Try Chrome, Edge, Firefox or Safari.": "Este navegador no puede mostrar notificaciones. Pruebe Chrome, Edge, Firefox o Safari.",
  "This deployment is missing its Supabase settings.": "A esta instalación le faltan los ajustes de Supabase.",
  "This gets scheduled during business hours.": "Esto se programa en horario laboral.",
  "This is an AI suggestion, not an inspection. If something feels dangerous, treat it as an emergency.": "Esto es una sugerencia de la IA, no una inspección. Si algo le parece peligroso, trátelo como emergencia.",
  "This needs help right now.": "Esto necesita ayuda ahora mismo.",
  "This only updates your own list.": "Esto solo actualiza su propia lista.",
  "This permanently deletes {place}, all of its requests and messages, and removes everyone from it.": "Esto elimina para siempre {place}, todas sus solicitudes y mensajes, y saca a todas las personas.",
  "This permanently deletes your account, your requests, photos, videos and messages. Properties where you're the only manager are deleted too. This can't be undone.": "Esto elimina para siempre su cuenta, sus solicitudes, fotos, videos y mensajes. También se eliminan las propiedades donde usted es el único administrador. No se puede deshacer.",
  "This person": "Esta persona",
  "This record is provided for your information and is not legal advice.": "Esta constancia es solo informativa y no es asesoría legal.",
  "This reset link is no longer valid. Request a new one.": "Este enlace ya no es válido. Pida uno nuevo.",
  "Times are recorded by CanItWait's server when each event happens and can't be edited by the resident or the manager. Messages appear as written.": "Las horas las registra el servidor de CanItWait en el momento de cada evento y ni el residente ni la administración pueden editarlas. Los mensajes aparecen tal como se escribieron.",
  "Title": "Título",
  "Too many attempts. Wait a minute and try again.": "Demasiados intentos. Espere un minuto e intente de nuevo.",
  "Took more than one visit": "Tomó más de una visita",
  "Translate to {language}": "Traducir al {language}",
  "Translated by AI from {language}": "Traducido por IA del {language}",
  "Translating…": "Traduciendo…",
  "Translation isn't available right now. Try again in a minute.": "La traducción no está disponible en este momento. Intente de nuevo en un minuto.",
  "Try another filter.": "Pruebe otro filtro.",
  "Try signing in, or request a new link.": "Intente iniciar sesión o pida un enlace nuevo.",
  "Try the AI check again": "Intentar la revisión con IA otra vez",
  "Trying CanItWait out?": "¿Está probando CanItWait?",
  "Type {name} to confirm": "Escriba {name} para confirmar",
  "Type DELETE to confirm": "Escriba DELETE para confirmar",
  "Unit": "Unidad",
  "Unnamed": "Sin nombre",
  "Until it's fixed": "Mientras lo arreglan",
  "Until then, keep signing in with {email}.": "Mientras tanto, siga iniciando sesión con {email}.",
  "updated": "actualizada",
  "updated {ago} ago": "actualizada hace {ago}",
  "updated just now": "actualizada ahora",
  "Uploading photo…": "Subiendo foto…",
  "Uploading video…": "Subiendo video…",
  "Urgency": "Urgencia",
  "Urgency changed by your team": "Su equipo cambió la urgencia",
  "Urgency changed from {from} to {to} {ago}.": "La urgencia cambió de {from} a {to} {ago}.",
  "Urgency set to {level}": "Urgencia cambiada a {level}",
  "Urgency updated by maintenance": "Mantenimiento actualizó la urgencia",
  "Urgent": "Urgente",
  "Use a password with at least 8 characters.": "Use una contraseña de al menos 8 caracteres.",
  "Use at least 8 characters for the new password.": "Use al menos 8 caracteres en la contraseña nueva.",
  "Use the app in your language. Requests and messages translate with one tap.": "Use la app en su idioma. Las solicitudes y los mensajes se traducen con un toque.",
  "Use this when the urgency is wrong. The resident sees the change, and Insights tracks how often the AI's call holds up.": "Use esto cuando la urgencia esté mal. El residente ve el cambio y Estadísticas registra qué tan seguido acierta la IA.",
  "Used only for the estimates above. Saved on this device.": "Solo se usan para los estimados de arriba. Se guardan en este dispositivo.",
  "Used to sign in with your email": "Se usa para iniciar sesión con su correo",
  "Usually 10 to 30 seconds. You can switch apps; CanItWait picks up when you come back.": "Normalmente de 10 a 30 segundos. Puede cambiar de app; CanItWait continúa cuando regrese.",
  "Video added ({s} s)": "Video agregado ({s} s)",
  "Video of the problem": "Video del problema",
  "View request": "Ver solicitud",
  "Visit {time}": "Visita {time}",
  "Visit date and time": "Fecha y hora de la visita",
  "Visit scheduled": "Visita programada",
  "Visit: {time}": "Visita: {time}",
  "Visits": "Visitas",
  "Waiting for you to confirm {email}": "Esperando que confirme {email}",
  "Waiting for your manager to see this emergency.": "Esperando que la administración vea esta emergencia.",
  "Waiting longer than its urgency allows": "Lleva esperando más de lo que permite su urgencia",
  "Want to see how it works? Load a sample property with six weeks of requests.": "¿Quiere ver cómo funciona? Cargue una propiedad de ejemplo con seis semanas de solicitudes.",
  "Water dripping from the bathroom ceiling over the sink, started tonight": "Gotea agua del techo del baño encima del lavamanos, empezó esta noche",
  "water or sewage you can't stop": "agua o aguas negras que no puede detener",
  "Water or sewage you can't stop?": "¿Agua o aguas negras que no puede detener?",
  "We sent a confirmation link to {email}. Open it in this browser to finish creating your account.": "Enviamos un enlace de confirmación a {email}. Ábralo en este navegador para terminar de crear su cuenta.",
  "We sent a confirmation link to {email}. Your email changes after you open it. If you also get a link at your current address, open that one too.": "Enviamos un enlace de confirmación a {email}. Su correo cambia después de abrirlo. Si también le llega un enlace a su dirección actual, ábralo también.",
  "We'll check the unit above yours too.": "También revisaremos la unidad de arriba.",
  "We'll email you a link to set a new password.": "Le enviaremos un enlace por correo para crear una contraseña nueva.",
  "Weekday afternoons": "Tardes entre semana",
  "Weekday mornings": "Mañanas entre semana",
  "Weekends": "Fines de semana",
  "Welcome to CanItWait": "Bienvenido a CanItWait",
  "What's going on?": "¿Qué está pasando?",
  "What's wrong?": "¿Qué pasa?",
  "When you report something, it shows up here with its status and any messages from maintenance.": "Cuando reporte algo, aparecerá aquí con su estado y los mensajes de mantenimiento.",
  "Where": "Dónde",
  "Where in your home?": "¿En qué parte de su vivienda?",
  "Which home?": "¿Qué vivienda?",
  "Why urgency was changed": "Por qué se cambió la urgencia",
  "Why?": "¿Por qué?",
  "WORK ORDER": "ORDEN DE TRABAJO",
  "Workspace": "Vista",
  "Worth checking whether the last fix held.": "Conviene revisar si el último arreglo funcionó.",
  "Written in {language}": "Escrito en {language}",
  "Written in {language}. Open it in CanItWait to translate.": "Escrito en {language}. Ábralo en CanItWait para traducirlo.",
  "Yes": "Sí",
  "you": "usted",
  "You": "Usted",
  "You already have an account with {email}.": "Ya tiene una cuenta con {email}.",
  "You already started an account with this email. Open the confirmation link we emailed you, then sign in.": "Ya empezó una cuenta con este correo. Abra el enlace de confirmación que le enviamos y luego inicie sesión.",
  "You answered yes to a safety question, so double-check this.": "Respondió que sí a una pregunta de seguridad, así que revíselo bien.",
  "You can add the other later in Settings.": "Puede agregar la otra opción después en Ajustes.",
  "You can go to bed": "Puede irse a dormir",
  "You can still send this. Your manager will see it marked for manual review.": "Igual puede enviarlo. La administración lo verá marcado para revisión manual.",
  "You cannot change this request": "No puede cambiar esta solicitud",
  "You changed this from {level}. Your manager will see both.": "Usted cambió esto de {level}. La administración verá ambos.",
  "You don't have access to do that.": "No tiene permiso para hacer eso.",
  "You get these because email updates are on in CanItWait settings.": "Recibe esto porque tiene activados los avisos por correo en los ajustes de CanItWait.",
  "You left the property": "Salió de la propiedad",
  "You may not manage this property anymore.": "Puede que ya no administre esta propiedad.",
  "You mentioned {things}. If that's happening right now, this is an emergency.": "Usted mencionó {things}. Si eso está pasando ahora mismo, es una emergencia.",
  "You mentioned this. Please answer.": "Usted mencionó esto. Por favor responda.",
  "You now manage {place}": "Ahora administra {place}",
  "You stopped the AI check.": "Usted detuvo la revisión con IA.",
  "You won't be able to report there until you join again with a code. Requests you already sent stay in your list.": "No podrá reportar ahí hasta que vuelva a unirse con un código. Las solicitudes que ya envió se quedan en su lista.",
  "You'll be signed out on every phone and computer, including this one. Use this if you lost a device or think someone else signed in.": "Se cerrará la sesión en todos los teléfonos y computadoras, incluido este. Úselo si perdió un dispositivo o cree que alguien más entró a su cuenta.",
  "You'll get a code to share with residents. You can add more properties later.": "Recibirá un código para compartir con los residentes. Puede agregar más propiedades después.",
  "You're all caught up": "Está al día",
  "You're filling this in yourself.": "Usted lo está llenando.",
  "You're joining with code {code}. We'll connect you after you sign in.": "Se está uniendo con el código {code}. Lo conectaremos después de iniciar sesión.",
  "You're offline or the server can't be reached. Try again.": "No tiene conexión o no se puede llegar al servidor. Intente de nuevo.",
  "Your account": "Su cuenta",
  "Your answer (optional)": "Su respuesta (opcional)",
  "Your costs": "Sus costos",
  "Your current password isn't right.": "Su contraseña actual no es correcta.",
  "Your emergency hasn't been seen yet": "Todavía no han visto su emergencia",
  "Your home": "Su vivienda",
  "your landlord": "su arrendador",
  "Your landlord doesn't use CanItWait, so updates won't appear here. Contact them directly, and mark it fixed here when it's done.": "Su arrendador no usa CanItWait, así que las novedades no aparecerán aquí. Contáctelo directamente y márquela como arreglada aquí cuando esté lista.",
  "Your manager has it now. You'll see updates and messages on the request.": "La administración ya la tiene. Verá las novedades y los mensajes en la solicitud.",
  "Your manager hasn't seen this yet. CanItWait alerted their backup contact.": "La administración aún no ha visto esto. CanItWait avisó a su contacto de respaldo.",
  "Your message has blanks maintenance will want filled in. Answer what you can; your answers go into the message.": "Su mensaje tiene espacios que mantenimiento querrá ver llenos. Responda lo que pueda; sus respuestas se agregan al mensaje.",
  "Your name goes on requests so maintenance knows who to contact.": "Su nombre aparece en las solicitudes para que mantenimiento sepa a quién contactar.",
  "Your new password is saved. Use it next time you sign in.": "Su nueva contraseña quedó guardada. Úsela la próxima vez que inicie sesión.",
  "Your photo of the problem": "Su foto del problema",
  "Your property": "Su propiedad",
  "Your property manager gives you this code.": "La administración de su propiedad le da este código.",
  "Your request": "Su solicitud",
  "Your request is now: {status}": "Su solicitud ahora está: {status}",
  "Your request is ready to send": "Su solicitud está lista para enviar",
  "Your requests, photos and videos are visible only to you and the managers of the property you sent them to.": "Sus solicitudes, fotos y videos solo los ven usted y la administración de la propiedad a la que los envió.",
  "Your role": "Su rol",
  "Your sign-in needs refreshing. Sign out and back in to use the AI check.": "Hay que renovar su sesión. Cierre sesión y vuelva a entrar para usar la revisión con IA.",
  "Your unit": "Su unidad",
  "Your urgency call": "Su evaluación de urgencia",
  "Your video is sent with the request.": "Su video se envía con la solicitud.",
};
